// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql/driver"
	"fmt"
)

type Myenum string

const (
	MyenumOne   Myenum = "one"
	MyenumTwo   Myenum = "two"
	MyenumThree Myenum = "three"
	MyenumFour  Myenum = "four"
)

func (e *Myenum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Myenum(s)
	case string:
		*e = Myenum(s)
	default:
		return fmt.Errorf("unsupported scan type for Myenum: %T", src)
	}
	return nil
}

type NullMyenum struct {
	Myenum Myenum `json:"myenum"`
	Valid  bool   `json:"valid"` // Valid is true if Myenum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMyenum) Scan(value interface{}) error {
	if value == nil {
		ns.Myenum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Myenum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMyenum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Myenum), nil
}

type DemoTable struct {
	ID      int32    `db:"id" json:"id"`
	Special []Myenum `db:"special" json:"special"`
}
