// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package database

import (
	"context"
)

const getAll = `-- name: GetAll :many
SELECT id, special FROM demo_table ORDER BY id
`

func (q *Queries) GetAll(ctx context.Context) ([]DemoTable, error) {
	rows, err := q.db.Query(ctx, getAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DemoTable
	for rows.Next() {
		var i DemoTable
		if err := rows.Scan(&i.ID, &i.Special); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertNewEntry = `-- name: InsertNewEntry :exec
INSERT INTO demo_table (
    special
) VALUES (
    $1
)
`

func (q *Queries) InsertNewEntry(ctx context.Context, special []Myenum) error {
	_, err := q.db.Exec(ctx, insertNewEntry, special)
	return err
}
